name: Palawan Tours
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f53b4'
    - '#9eacb1'
    - '#fef8ea'
    - '#6778af'
    - '#181398'
  brandStrength: 0.20503194397315383
  lightness: 0.45420327549800277
  saturation: 0.5279669151641428
  rhythmicContrast: 0.4319332060404122
purpose: []
